
language: node_js
node_js:
  - "lts/*"
install:
  - npm install 
  - lerna bootstrap
dist: trusty
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=c8ed0722e6e2eb42ee8b9618cbcc4d56ff2c12d6b449541586bf5cb36247abf9
before_script:
  # Commented out for local testing only on MacOS
  #- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - lerna run test
after_script:
  # See https://github.com/codeclimate/test-reporter/issues/263
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      for f in packages/*; do
        if [ -d $f ]; then
          echo $f;
          ./cc-test-reporter format-coverage -t lcov -o coverage/coverage.${f//\//-}.json $f/coverage/lcov.info;
        fi
      done;
      ./cc-test-reporter sum-coverage -o coverage/coverage.total.json coverage/coverage.*.json;
      ./cc-test-reporter upload-coverage -i coverage/coverage.total.json;
    fi
