version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/fast-dna
    steps:
      - checkout
      - run:
          name: Install the latest NPM version and patches
          command: |
            sudo npm i npm@latest -g
            npm update rc --depth 4
      - run:
          name: Install the latest Lerna version
          command: |
            sudo npm i lerna@latest -g
      - restore_cache:
          keys:
          - v1-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install all dependency packages
          command: |
            npm i
      - run:
          name: Execute Lerna bootstrap
          command: |
            lerna bootstrap
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules   
            
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run: lerna run test --stream
 
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
  
