name: CD - Creator

on:
  push:
    branches:
    - master

jobs:
  build_linux:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_ACTIVE_STAGE_NAME: create-west-app
      AZURE_WEBAPP_PASSIVE_STAGE_NAME: create-east-app
      AZURE_WEBAPP_BUILD_PATH: sites/fast-creator/www
      AZURE_WEBAPP_SLOT_NAME: stage

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_FAST_DESIGN }}

    - name: Checkout Branch
      uses: actions/checkout@master

    - name: Install Lerna
      run: sudo yarn global add lerna

    - name: Install package dependencies / prepare workspaces
      run: yarn install --frozen-lockfile
    
    - name: Build Web Application
      run: |
        cd ${{ env.AZURE_WEBAPP_BUILD_PATH }}
        yarn build

    - name: 'Deploy to Active Azure Region'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_ACTIVE_STAGE_NAME }}
        package: ${{ env.AZURE_WEBAPP_BUILD_PATH }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}

    - name: 'Deploy to Passive Azure Region'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_PASSIVE_STAGE_NAME }}
        package: ${{ env.AZURE_WEBAPP_BUILD_PATH }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}

    - name: Azure Logout
      run: |
        az logout