name: CI - FAST Publish

on:
  pull_request:
    branches:
    - master
  # schedule:
  # - cron: 0 12 * * 7

jobs:
  build_linux:
    runs-on: ubuntu-latest

    env:
      NPM_PAT: ${{ secrets.PACK_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_SERVICE_PAT: ${{ secrets.GH_PAT }}
      GITHUB_SERVICE_USER: "Microsoft FAST Builds"
      GITHUB_SERVICE_EMAIL: "fastdna@service.microsoft.com"

    steps:
    - uses: actions/checkout@v2

    - name: Add or Update packages
      run: sudo yarn global add lerna

    - name: Authenticate Git for Pushes
      run: |
        git config --global user.name "${{ env.GITHUB_SERVICE_USER }}"
        git config --global user.email "${{ env.GITHUB_SERVICE_EMAIL }}"
    
    - name: Install package dependencies / prepare workspaces
      run: yarn install --frozen-lockfile

    - name: Testing Prettier format
      run: lerna run prettier:diff

    - name: Testing unit tests
      run: lerna run test --stream   
      
    - name: Publish NPM changed packages
      run: |
        yarn publish-ci -y -n $NAT_PAT
      ## If the global NAT_PAT env variable doesn't appear here, then uncomment below to activate it for this specific task
      # env: 
      #   NPM_PAT: ${{ secrets.PACK_TOKEN }}
