name: CI - FAST Publish

on:
  pull_request:
    branches:
    - master
  # schedule:
  # - cron: 0 12 * * 7

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add or Update packages
      run: sudo yarn global add lerna

    - name: Authenticate Git for Pushes
      run: |
        git config user.name ${{ env.GITHUB_PUBLISH_USER }}
        git config user.email ${{ env.GITHUB_PUBLISH_EMAIL }}
    
    - name: Install package dependencies / prepare workspaces
      run: yarn install --frozen-lockfile

    - name: Testing Prettier format
      run: lerna run prettier:diff

    - name: Testing unit tests
      run: lerna run test --stream   
      
    - name: Publish NPM changed packages
      run: |
        npm run beachball-publish -- -b origin/master -n ${{ env.NPM_PAT }} --access public -y
        git reset --hard origin/master
    