name: CI - FAST Validation

on:
  schedule:
  - cron: 0 7 * * 3
  push: 
  - master
  - ci-os-validation
  pull_request:
  - master 
  - ci-os-validation

Jobs: 
  node_version:
    strategy:
      matrix:
        os:[windows-latest, macos-latest]
        node_version: [10,12]

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
        node-version: ${{matrix.node_version}}

    - name: Install Lerna
      run: npm i -g lerna

    - name: Install package dependencies / prepare workspaces
      run: |
        yarn install --frozen-lockfile

    - name: Ensure Prettier formatting
      run: lerna run prettier:diff

    - name: Execute unit tests
      run: lerna run test --stream

  code_scan:
    name: Validate Security

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1