name: Azure DevOps Actions

on: 
  push:
    branches:
    - master
    - releases/*

jobs:
  build_azure_pipelines:
    name: Build Azure Pipelines
    runs-on: ubuntu-latest  
    
    steps:
     - name: Trigger an Azure Pipeline
       uses: Azure/pipelines@v1
       with:
         azure-devops-project-url: https://dev.azure.com/edgewebui/fast-dna
         azure-pipeline-name: fast.web.build
         azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

     - name: Setup Node 12.14.x
       uses: actions/setup-node@v1
       with:
         node-version: '12.14.x'