name: FAST Workflows

on:
  push: 
    branches:
    - master
    - releases/*
  pull_request:
    branches:
    - master
    - releases/*

jobs:
  build_linux:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Lerna
      run: sudo yarn global add lerna@3.18.2  

    - name: Install package dependencies
      run: yarn install --frozen-lockfile

    - name: Build Yarn workspaces
      run: lerna run prepare

    - name: Ensure Prettier formatting
      run: lerna run prettier:diff

    - name: Execute unit tests
      run: lerna run test --stream
      
  code_coverage:

    needs: [ build_linux ]
    name: coverage

    steps:
    - uses: paambaati/codeclimate-action@v2.5.2
      env:
        CC_TEST_REPORTER_id: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
      with:
        coverageCommand: yarn coverage
