name: "PR - FAST"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint_title:
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.0
